Repository RetroBat-Official/emulatorlauncher, pull requests merged in 2024-01, with the labels that each got.

#269 PSX on libretro, kronos and genesis plus gx
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Duckstation.Generator.cs
  emulatorLauncher/Generators/Kronos.Generator.cs
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
Labels: enhancement

#270 Add GZDOOM
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/GzDoom.Generator.cs
  emulatorLauncher/Installer.cs
  emulatorLauncher/Program.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: enhancement

#272 Wheels very beginning (class + first method to get wheels with few identified PID/VID)
  EmulatorLauncher.Common/EmulatorLauncher.Common.csproj
  EmulatorLauncher.Common/Wheels/RawWheels.cs
Labels: enhancement

#273 Few libretro core options fixes
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
Labels: bug, enhancement

#274 gzdoom add savepath
  emulatorLauncher/Generators/GzDoom.Generator.cs
Labels: enhancement

#275 Dolphin - add shader compilation method
  .emulationstation/es_features.cfg
Labels: enhancement

#276 HDR - only allow with D3D video drivers
  emulatorLauncher/Generators/LibRetro.Generator.cs
Labels: enhancement

#277 Manage HDR in dolphin and gzdoom + disable update check in mgba
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Dolphin.Generator.cs
  emulatorLauncher/Generators/GzDoom.Generator.cs
  emulatorLauncher/Generators/mGBA.Generator.cs
Labels: enhancement

#278 Kronos : fix + controller correction
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Kronos.Controllers.cs
  emulatorLauncher/Generators/Kronos.Generator.cs
Labels: enhancement

#279 Add kronos hotkeys
  emulatorLauncher/Generators/Kronos.Controllers.cs
Labels: enhancement

#280 Fix dolphin vsync
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Dolphin.Generator.cs
Labels: bug

#281 add vulkan driver compatibility (driver & shaders)
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Snes9x.Generator.cs
Labels: enhancement

#284 Add melonds DS core
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
Labels: enhancement

#285 bizhawk to sdl
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/EmulatorLauncher.Common.csproj
  EmulatorLauncher.Common/Joysticks/SdlToDirectInput.cs
  emulatorLauncher/Generators/Bizhawk.Controllers.cs
  emulatorLauncher/Generators/Bizhawk.CoreOptions.cs
  emulatorLauncher/Generators/Bizhawk.Generator.cs
  emulatorLauncher/Generators/Bizhawk.Guns.cs
Labels: enhancement

#286 yuzu handheld fix, gzdoom mods, bizhawk saturn fix
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Bizhawk.CoreOptions.cs
  emulatorLauncher/Generators/GzDoom.Generator.cs
  emulatorLauncher/Generators/Kronos.Generator.cs
  emulatorLauncher/Generators/Yuzu.Controllers.cs
  emulatorLauncher/Generators/Yuzu.Generator.cs
Labels: bug

#287 Allow HDR for vulkan also
  emulatorLauncher/Generators/LibRetro.Generator.cs
Labels: enhancement

#288 2 fixes (citra & lr-flycast) + 1 enhancement (redream)
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Citra.Generator.cs
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
  emulatorLauncher/Generators/Redream.Generator.cs
Labels: bug, enhancement

#289 Few fixes
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/LibRetro.Generator.cs
  emulatorLauncher/Generators/VPinball.Generator.cs
Labels: bug, enhancement

#290 Supermodel and gzdoom
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/GzDoom.Generator.cs
  emulatorLauncher/Generators/Model3.Generator.cs
Labels: bug, enhancement

#292 Fix some windows games going back to ES
  emulatorLauncher/Generators/ExeLauncher.Generator.cs
Labels: bug

#295 Small fixes
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Dolphin.Generator.cs
  emulatorLauncher/Generators/Rpcs3.Generator.cs
  emulatorLauncher/Generators/Xenia.Generator.cs
Labels: bug, enhancement

#296 Add dinput to model3
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/BigPEmu.Generator.cs
  emulatorLauncher/Generators/Bizhawk.Generator.cs
  emulatorLauncher/Generators/Cemu.Generator.cs
  emulatorLauncher/Generators/Citra.Generator.cs
  emulatorLauncher/Generators/Flycast.Generator.cs
  emulatorLauncher/Generators/Model3.Controllers.cs
Labels: enhancement

#298 Flycast and windows
  emulatorLauncher/Generators/ExeLauncher.Generator.cs
  emulatorLauncher/Generators/Flycast.Controllers.cs
  emulatorLauncher/Generators/Flycast.Generator.cs
Labels: enhancement

#299 mame64 and supermodel
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Mame64.Generator.cs
  emulatorLauncher/Generators/Model3.Controllers.cs
Labels: bug, enhancement

#300 Add few logs to dolphin generator
  emulatorLauncher/Generators/Dolphin.Controllers.cs
  emulatorLauncher/Generators/Dolphin.Generator.cs
Labels: enhancement

#302 Zinc controllers + pause on disconnect in retroarch
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/Joysticks/SdlToDirectInput.cs
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
  emulatorLauncher/Generators/LibRetro.Generator.cs
  emulatorLauncher/Generators/Model3.Controllers.cs
  emulatorLauncher/Generators/Zinc.Controllers.cs
Labels: enhancement

#305 Model2, model3 and zinc
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Model2.Controllers.cs
  emulatorLauncher/Generators/Model3.Controllers.cs
  emulatorLauncher/Generators/Zinc.Generator.cs
Labels: bug, enhancement

#306 Model 2 : ratio + keyboard
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Model2.Controllers.cs
  emulatorLauncher/Generators/Model2.Generator.cs
Labels: bug, enhancement

#307 SSF configure controllers
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/SSF.Controllers.cs
  emulatorLauncher/Generators/SSF.Generator.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: enhancement

#308 Wheel for model3
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/EmulatorLauncher.Common.csproj
  EmulatorLauncher.Common/Properties/Resources.Designer.cs
  EmulatorLauncher.Common/Properties/Resources.resx
  EmulatorLauncher.Common/Wheels/RawWheels.cs
  EmulatorLauncher.Common/Wheels/wheels.yml
  emulatorLauncher/Generators/Model2.Controllers.cs
  emulatorLauncher/Generators/Model3.Controllers.cs
Labels: enhancement

#310 Wheels model3 cleaning
  EmulatorLauncher.Common/Wheels/RawWheels.cs
  emulatorLauncher/Generators/Model3.Controllers.cs
Labels: enhancement

#312 Wheels refactoring + fix nullpointer in zinc
  EmulatorLauncher.Common/EmulatorLauncher.Common.csproj
  EmulatorLauncher.Common/Properties/Resources.Designer.cs
  EmulatorLauncher.Common/Properties/Resources.resx
  emulatorLauncher/Common/Wheels.cs
  emulatorLauncher/Generators/Model3.Controllers.cs
  emulatorLauncher/Generators/Zinc.Controllers.cs
  emulatorLauncher/Generators/Zinc.Generator.cs
  emulatorLauncher/Program.cs
  emulatorLauncher/Properties/Resources.Designer.cs
  emulatorLauncher/Properties/Resources.resx
  emulatorLauncher/Resources/wheelMapping.yml
  emulatorLauncher/emulatorLauncher.csproj
Labels: enhancement

#313 Wheels for pcsx2
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/Joysticks/SdlToDirectInput.cs
  emulatorLauncher/Common/Wheels.cs
  emulatorLauncher/Generators/Duckstation.Controllers.cs
  emulatorLauncher/Generators/Duckstation.Guns.cs
  emulatorLauncher/Generators/Model3.Controllers.cs
  emulatorLauncher/Generators/Pcsx2.Controllers.cs
  emulatorLauncher/Generators/Pcsx2.Generator.cs
  emulatorLauncher/Generators/Pcsx2.Guns.cs
  emulatorLauncher/Generators/Pcsx2.Wheels.cs
  emulatorLauncher/Properties/Resources.Designer.cs
  emulatorLauncher/Properties/Resources.resx
  emulatorLauncher/Resources/wheelMapping.yml
  emulatorLauncher/Resources/wheelSDLMapping.yml
  emulatorLauncher/emulatorLauncher.csproj
Labels: enhancement

#314 Multiple fixes and wheel stuff
  .emulationstation/es_features.cfg
  emulatorLauncher/Common/Wheels.cs
  emulatorLauncher/Generators/Flycast.Controllers.cs
  emulatorLauncher/Generators/Flycast.Guns.cs
  emulatorLauncher/Generators/Model2.Controllers.cs
  emulatorLauncher/Generators/Model3.Controllers.cs
  emulatorLauncher/Generators/Pcsx2.Wheels.cs
  emulatorLauncher/Generators/PinballFX.Generator.cs
  emulatorLauncher/Generators/PinballFX3.Generator.cs
  emulatorLauncher/Generators/Rpcs3.Generator.cs
  emulatorLauncher/Generators/Rpcs3.Guns.cs
  emulatorLauncher/Program.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: bug, enhancement

#315 Add pinballM
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/PinballFX.Generator.cs
Labels: enhancement

#316 Fix pcsx2 forcefeedback
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Pcsx2.Wheels.cs
  emulatorLauncher/Resources/wheelMapping.yml
  emulatorLauncher/Resources/wheelSDLMapping.yml
Labels: enhancement

#319 SDL controllers fixes + SNES9X
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Ares.Controllers.cs
  emulatorLauncher/Generators/Model2.Controllers.cs
  emulatorLauncher/Generators/Model3.Controllers.cs
  emulatorLauncher/Generators/Pcsx2.Wheels.cs
  emulatorLauncher/Generators/SSF.Controllers.cs
  emulatorLauncher/Generators/Snes9x.Controllers.cs
  emulatorLauncher/Generators/Snes9x.Generator.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: bug, enhancement

#320 Play! controllers
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Play.Controllers.cs
  emulatorLauncher/Generators/Play.Generator.cs
  emulatorLauncher/Generators/Rpcs3.Controllers.cs
  emulatorLauncher/Generators/SSF.Controllers.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: enhancement

#322 Dinput additions
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/Joysticks/SdlToDirectInput.cs
  emulatorLauncher/Controller.cs
  emulatorLauncher/Generators/Libretro.Controllers.cs
  emulatorLauncher/Generators/OpenMSX.Controllers.cs
  emulatorLauncher/Generators/Play.Controllers.cs
  emulatorLauncher/Generators/SSF.Controllers.cs
  emulatorLauncher/Generators/Snes9x.Controllers.cs
  emulatorLauncher/Generators/ZEsarUX.Controllers.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: enhancement

#324 Kega fusion controllers
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/Joysticks/DirectInputInfo.cs
  emulatorLauncher/Generators/KegaFusion.Controllers.cs
  emulatorLauncher/Generators/KegaFusion.Generator.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: enhancement

#326 Daphne hypseus autoconfig controllers
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Daphne.Controllers.cs
  emulatorLauncher/Generators/Daphne.Generator.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: enhancement

#328 Mame controllers and zaccaria fix
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/ZaccariaPinball.Generator.cs
Labels: bug, enhancement
