Repository RetroBat-Official/emulatorlauncher, pull requests merged in 2024-10, with the labels that each got.

#654 Ports - commander genius controls
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/FileTools.cs
  emulatorLauncher/Generators/PortsLauncher.Configuration.cs
  emulatorLauncher/Generators/PortsLauncher.Controllers.cs
  emulatorLauncher/Generators/PortsLauncher.Generator.cs
Labels: enhancement

#660 Ports and sliders
  emulatorLauncher/Common/Generator.cs
  emulatorLauncher/Generators/PortsLauncher.Generator.cs
Labels: bug, enhancement

#661 Bizhawk and BigPEmu
  .emulationstation/es_savestates.cfg
  emulatorLauncher/Generators/BigPEmu.Controllers.cs
  emulatorLauncher/Generators/BigPEmu.Generator.cs
  emulatorLauncher/Generators/BigPemu.SaveStatesMonitor.cs
  emulatorLauncher/Generators/Bizhawk.Controllers.cs
  emulatorLauncher/Generators/Bizhawk.Generator.cs
  emulatorLauncher/Generators/Bizhawk.SaveStatesMonitor.cs
  emulatorLauncher/Generators/OpenMSX.Generator.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: bug, enhancement

#665 snes9x + newtonsoft
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/EmulatorLauncher.Common.csproj
  EmulatorLauncher.Common/StringExtensions.cs
  Newtonsoft.Json.dll
  batocera-ports.sln
  emulatorLauncher/Common/Generator.cs
  emulatorLauncher/Generators/Snes9x.Controllers.cs
  emulatorLauncher/Generators/Snes9x.Generator.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: enhancement

#666 Copy output dll newtonsoft
  emulatorLauncher/emulatorLauncher.csproj
Labels: enhancement

#667 Update appveyor.yml
  build/appveyor.yml
Labels: enhancement

#671 Switches and sliders
  .emulationstation/es_features.cfg
  emulatorLauncher/Common/Generator.cs
  emulatorLauncher/Generators/Fbneo.Controllers.cs
  emulatorLauncher/Generators/Flycast.Controllers.cs
  emulatorLauncher/Generators/ForceEngine.Generator.cs
  emulatorLauncher/Generators/Libretro.Controllers.cs
  emulatorLauncher/Generators/Libretro.InputRemap.cs
  emulatorLauncher/Generators/Model3.Controllers.cs
  emulatorLauncher/Generators/Model3.Generator.cs
  emulatorLauncher/Generators/OpenBor.Generator.cs
  emulatorLauncher/Generators/PortsLauncher.Configuration.cs
  emulatorLauncher/Generators/Raine.Generator.cs
  emulatorLauncher/Generators/Rpcs3.Generator.cs
  emulatorLauncher/Generators/ShadPS4.Generator.cs
  emulatorLauncher/Generators/Simple64.Controllers.cs
  emulatorLauncher/Generators/Singe2.Generator.cs
  emulatorLauncher/Generators/Stella.Generator.cs
  emulatorLauncher/Generators/Sudachi.Controllers.cs
  emulatorLauncher/Generators/Sudachi.Generator.cs
  emulatorLauncher/Generators/Suyu.Controllers.cs
  emulatorLauncher/Generators/Suyu.Generator.cs
  emulatorLauncher/Generators/TeknoParrot.generator.cs
  emulatorLauncher/Generators/Uae.Generator.cs
  emulatorLauncher/Generators/VPinball.Generator.cs
  emulatorLauncher/Generators/Xemu.Generator.cs
  emulatorLauncher/Generators/Xenia.Generator.cs
  emulatorLauncher/Generators/Yuzu.Controllers.cs
  emulatorLauncher/Generators/Yuzu.Generator.cs
  emulatorLauncher/Generators/Zinc.Controllers.cs
  emulatorLauncher/Generators/Zinc.Generator.cs
  emulatorLauncher/Generators/vita3k.Generator.cs
Labels: bug, enhancement

#672 Add vircon32
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
Labels: enhancement

#673 Add raze
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Raze.Generator.cs
  emulatorLauncher/Installer.cs
  emulatorLauncher/Program.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: enhancement

#674 softpatching and model2
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/EmulationStation/EsFeatures.cs
  emulatorLauncher/Generators/GzDoom.Generator.cs
  emulatorLauncher/Generators/LibRetro.Generator.cs
  emulatorLauncher/Generators/Model2.Controllers.cs
  emulatorLauncher/Generators/Raze.Generator.cs
Labels: enhancement

#675 rpcs3 and mesen
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Mesen.Generator.cs
  emulatorLauncher/Generators/Rpcs3.Generator.cs
Labels: enhancement

#676 Add option to control fast forward ratio
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/LibRetro.Generator.cs
  emulatorLauncher/Generators/Libretro.Controllers.cs
Labels: enhancement

#677 Fix patches in subfolder
  emulatorLauncher/Generators/LibRetro.Generator.cs
Labels: bug

#678 2 fixes
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/ExeLauncher.Generator.cs
Labels: bug

#679 Ares - fix exit error
  emulatorLauncher/Generators/Ares.Generator.cs
Labels: bug

#681 Model2 - fix shoulder option
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Model2.Controllers.cs
Labels: enhancement

#682 Fpinball - add padtokey when using BAM
  emulatorLauncher/Generators/Fpinball.Generator.cs
Labels: enhancement

#683 Model 2 and redream
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Model2.Controllers.cs
  emulatorLauncher/Generators/Model3.Controllers.cs
  emulatorLauncher/Generators/Redream.Generator.cs
Labels: enhancement

#684 Try fix of ship of harkinian controls for arcade
  emulatorLauncher/Generators/PortsLauncher.Controllers.cs
Labels: bug

#685 Error in soh fix
  emulatorLauncher/Generators/PortsLauncher.Controllers.cs
Labels: bug

#686 PPSSPP add language feature
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Ppsspp.Generator.cs
Labels: enhancement

#687 Add debug logs for soh
  emulatorLauncher/Generators/PortsLauncher.Controllers.cs
Labels: bug

#688 Fixes and features
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/ExeLauncher.Generator.cs
  emulatorLauncher/Generators/LibRetro.Generator.cs
  emulatorLauncher/Generators/Mame64.Controllers.cs
  emulatorLauncher/Generators/PortsLauncher.Configuration.cs
  emulatorLauncher/Generators/PortsLauncher.Controllers.cs
  emulatorLauncher/Generators/PortsLauncher.Generator.cs
  emulatorLauncher/Generators/ScummVm.Generator.cs
  emulatorLauncher/Installer.cs
  emulatorLauncher/Program.cs
Labels: bug, enhancement

#689 Add openjazz + MAME
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
  emulatorLauncher/Generators/MessSystem.cs
  emulatorLauncher/Generators/PortsLauncher.Generator.cs
  emulatorLauncher/Program.cs
Labels: enhancement

#690 MAME - add videopac - odyssey2 machine (MESS)
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Libretro.Controllers.cs
  emulatorLauncher/Generators/MessSystem.cs
Labels: enhancement

#691 Add feature on Xenia
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Xenia.Generator.cs
Labels: enhancement

#692 Change fix odyssey2 machine names
  .emulationstation/es_features.cfg
Labels: enhancement

#693 VG5K + fix dolphin dualsense
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/Joysticks/SdlJoystickGuid.cs
  emulatorLauncher/Generators/Dolphin.Controllers.cs
  emulatorLauncher/Generators/MessSystem.cs
Labels: bug, enhancement
