Repository RetroBat-Official/emulatorlauncher, pull requests merged in 2025-01, with the labels that each got.

#741 kronos, xemu, dolphin and bizhawk
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Bizhawk.Controllers.cs
  emulatorLauncher/Generators/Dolphin.Generator.cs
  emulatorLauncher/Generators/Kronos.Generator.cs
  emulatorLauncher/Generators/Xemu.Generator.cs
Labels: bug, enhancement

#743 Add Starship
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/LibRetro.Generator.cs
  emulatorLauncher/Generators/PortsLauncher.Configuration.cs
  emulatorLauncher/Generators/PortsLauncher.Generator.cs
  emulatorLauncher/Installer.cs
  emulatorLauncher/Program.cs
Labels: feature request

#744 Update es_features.cfg
  .emulationstation/es_features.cfg
Labels: bug

#745 Shad + controller fixes
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Demul.Controllers.cs
  emulatorLauncher/Generators/Demul.Generator.cs
  emulatorLauncher/Generators/Dolphin.Controllers.cs
  emulatorLauncher/Generators/Dolphin.Generator.cs
  emulatorLauncher/Generators/Kronos.Controllers.cs
  emulatorLauncher/Generators/Mesen.Generator.cs
  emulatorLauncher/Generators/Model2.Controllers.cs
  emulatorLauncher/Generators/ShadPS4.Generator.cs
  emulatorLauncher/Generators/Snes9x.Controllers.cs
  emulatorLauncher/Generators/Snes9x.Generator.cs
  emulatorLauncher/Generators/Yabasanshiro.Controllers.cs
Labels: bug, feature request

#746 Fix mednafen controllers
  EmulatorLauncher.Common/Joysticks/SdlJoystickGuid.cs
  EmulatorLauncher.Common/Joysticks/XInputDevice.cs
  emulatorLauncher/Generators/Bizhawk.Controllers.cs
  emulatorLauncher/Generators/Mednafen.Controllers.cs
Labels: bug

#750 Fix dolphin and add some lightguns to the database
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/Lightguns/RawLightGun.cs
  emulatorLauncher/Generators/Dolphin.Controllers.cs
  emulatorLauncher/Generators/Dolphin.Generator.cs
Labels: bug, enhancement

#751 Teknoparrot controls
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/Joysticks/XInputDevice.cs
  emulatorLauncher/Generators/TeknoParrot.Controllers.cs
  emulatorLauncher/Generators/TeknoParrot.Guns.cs
  emulatorLauncher/Teknoparrot/JoystickMapping.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: enhancement

#752 Teknoparrot manage multiplayer
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/TeknoParrot.Controllers.cs
Labels: enhancement

#753 Teknoparrot - fix Xinput Index
  emulatorLauncher/Generators/TeknoParrot.Controllers.cs
  emulatorLauncher/Generators/TeknoParrot.Guns.cs
  emulatorLauncher/Generators/TeknoParrot.generator.cs
  emulatorLauncher/Teknoparrot/JoystickMapping.cs
Labels: bug

#754 Teknoparrot guns - step 1 - get logs for names of devices
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/FileFormats/SimpleBml.cs
  EmulatorLauncher.Common/FileFormats/SimpleYml.cs
  EmulatorLauncher.Common/Joysticks/XInputDevice.cs
  emulatorLauncher/Generators/TeknoParrot.Controllers.cs
  emulatorLauncher/Generators/TeknoParrot.Guns.cs
Labels: enhancement, feature request

#755 Fix teknoparrot
  emulatorLauncher/Generators/TeknoParrot.Controllers.cs
  emulatorLauncher/Generators/TeknoParrot.generator.cs
  emulatorLauncher/Teknoparrot/JoystickMapping.cs
Labels: bug

#756 Teknoparrot guns - trial 1
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/Joysticks/RawInputDevice.cs
  EmulatorLauncher.Common/Lightguns/RawLightGun.cs
  emulatorLauncher/Generators/TeknoParrot.Controllers.cs
  emulatorLauncher/Generators/TeknoParrot.Guns.cs
  emulatorLauncher/Generators/TeknoParrot.generator.cs
Labels: enhancement, feature request

#757 Guns TP - wiimotegun
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/TeknoParrot.Controllers.cs
  emulatorLauncher/Generators/TeknoParrot.Guns.cs
  emulatorLauncher/Generators/TeknoParrot.generator.cs
  emulatorLauncher/Teknoparrot/GameProfile.cs
Labels: bug, enhancement

#758 TP : fix multiplayer guns
  emulatorLauncher/Generators/TeknoParrot.Controllers.cs
  emulatorLauncher/Generators/TeknoParrot.Guns.cs
Labels: bug

#759 Fix teknoparrot multigun ==> part 4
  emulatorLauncher/Controller.cs
  emulatorLauncher/Generators/LibRetro.Guns.cs
  emulatorLauncher/Generators/TeknoParrot.Controllers.cs
  emulatorLauncher/Generators/TeknoParrot.Guns.cs
Labels: bug, enhancement

#760 PCE + teknoparrot guns + flycast guns
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Flycast.Controllers.cs
  emulatorLauncher/Generators/Flycast.Guns.cs
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
  emulatorLauncher/Generators/LibRetro.Guns.cs
  emulatorLauncher/Generators/Mednafen.Generator.cs
  emulatorLauncher/Generators/TeknoParrot.Guns.cs
Labels: bug, enhancement

#761 Guns : integrate demulshooter and fix model2
  .emulationstation/es_features.cfg
  emulatorLauncher/Demulshooter/Demulshooter.cs
  emulatorLauncher/Generators/Model2.Controllers.cs
  emulatorLauncher/Generators/Model2.Generator.cs
  emulatorLauncher/Generators/Model2.Guns.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: enhancement, feature request

#762 Gun stuff : TP and model2
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Model2.Controllers.cs
  emulatorLauncher/Generators/Model2.Generator.cs
  emulatorLauncher/Generators/Model2.Guns.cs
  emulatorLauncher/Generators/TeknoParrot.Guns.cs
Labels: bug, enhancement

#763 Wheels and guns
  .emulationstation/es_features.cfg
  emulatorLauncher/Common/Wheels.cs
  emulatorLauncher/Generators/Flycast.Controllers.cs
  emulatorLauncher/Generators/Flycast.Wheels.cs
  emulatorLauncher/Generators/Model3.Controllers.cs
  emulatorLauncher/Generators/Pcsx2.Wheels.cs
  emulatorLauncher/Generators/TeknoParrot.generator.cs
  emulatorLauncher/Resources/wheelMapping.yml
  emulatorLauncher/Resources/wheelSDLMapping.yml
Labels: enhancement, feature request

#765 Fix teknoparrot reshade
  emulatorLauncher/Generators/TeknoParrot.Guns.cs
  emulatorLauncher/Generators/TeknoParrot.generator.cs
Labels: bug, enhancement

#766 Fix some null pointers in teknoparrot
  emulatorLauncher/Generators/Model2.Controllers.cs
  emulatorLauncher/Generators/TeknoParrot.Controllers.cs
  emulatorLauncher/Generators/TeknoParrot.Guns.cs
  emulatorLauncher/Generators/TeknoParrot.generator.cs
Labels: enhancement

#767 Model2 wheels
  .emulationstation/es_features.cfg
  emulatorLauncher/Common/Wheels.cs
  emulatorLauncher/Generators/Model2.Controllers.cs
Labels: enhancement

#768 TP reshade
  emulatorLauncher/Generators/TeknoParrot.generator.cs
Labels: bug

#773 Demulshooter + teknoparrot fixes
  .emulationstation/es_features.cfg
  emulatorLauncher/Demulshooter/Demulshooter.cs
  emulatorLauncher/Generators/TeknoParrot.generator.cs
Labels: bug, enhancement

#776 Gun stuff, demulshooter
  .emulationstation/es_features.cfg
  emulatorLauncher/Demulshooter/Demulshooter.cs
  emulatorLauncher/Generators/Model2.Guns.cs
  emulatorLauncher/Generators/TeknoParrot.Controllers.cs
  emulatorLauncher/Generators/TeknoParrot.Guns.cs
  emulatorLauncher/Generators/TeknoParrot.generator.cs
Labels: enhancement

#778 CITRA et lime3ds inversion boutons
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Citra.Controllers.cs
  emulatorLauncher/Generators/Lime3ds.Controllers.cs
Labels: enhancement

#779 Add support DemulShooter / Mamehook / Automatic COM Port Management
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/EmulatorLauncher.Common.csproj
  EmulatorLauncher.Common/FileFormats/MameHookerIni.cs
  EmulatorLauncher.Common/Lightguns/LightgunComPort.cs
  EmulatorLauncher.Common/Lightguns/RawLightGun.cs
  emulatorLauncher/Demulshooter/Demulshooter.cs
  emulatorLauncher/Generators/Demul.Generator.cs
  emulatorLauncher/Generators/ExeLauncher.Generator.cs
  emulatorLauncher/Generators/ExeLauncher.Guns.cs
  emulatorLauncher/Generators/Flycast.Guns.cs
  emulatorLauncher/Generators/Mame64.Generator.cs
  emulatorLauncher/Generators/Model3.Generator.cs
  emulatorLauncher/MameHooker/MameHooker.Demul.cs
  emulatorLauncher/MameHooker/MameHooker.ExeLauncher.cs
  emulatorLauncher/MameHooker/MameHooker.Flycast.cs
  emulatorLauncher/MameHooker/MameHooker.Mame64.cs
  emulatorLauncher/MameHooker/MameHooker.Model2.cs
  emulatorLauncher/MameHooker/MameHooker.Model3.cs
  emulatorLauncher/MameHooker/MameHooker.Teknoparrot.cs
  emulatorLauncher/MameHooker/MameHooker.cs
  emulatorLauncher/emulatorLauncher.csproj
Labels: feature request

#781 Mamehooker updates
  .emulationstation/es_features.cfg
  EmulatorLauncher.Common/EmulatorLauncher.Common.csproj
  EmulatorLauncher.Common/FileFormats/MameHookerIni.cs
  EmulatorLauncher.Common/Lightguns/LightgunComPort.cs
  emulatorLauncher/Demulshooter/Demulshooter.cs
  emulatorLauncher/Generators/Citra.Controllers.cs
  emulatorLauncher/Generators/Demul.Generator.cs
  emulatorLauncher/Generators/ExeLauncher.Generator.cs
  emulatorLauncher/Generators/ExeLauncher.Guns.cs
  emulatorLauncher/Generators/Flycast.Generator.cs
  emulatorLauncher/Generators/Flycast.Guns.cs
  emulatorLauncher/Generators/Mame64.Generator.cs
  emulatorLauncher/Generators/Model2.Generator.cs
  emulatorLauncher/Generators/Model2.Guns.cs
  emulatorLauncher/Generators/Model3.Generator.cs
  emulatorLauncher/Generators/TeknoParrot.generator.cs
Labels: feature request

#782 Fix exelauncher for mamehooker
  .emulationstation/es_features.cfg
  emulatorLauncher/Demulshooter/Demulshooter.cs
  emulatorLauncher/Generators/BigPEmu.Controllers.cs
  emulatorLauncher/Generators/Demul.Generator.cs
  emulatorLauncher/Generators/ExeLauncher.Guns.cs
Labels: enhancement

#783 Add log
  emulatorLauncher/Generators/ExeLauncher.Guns.cs
Labels: enhancement

#784 Add detection of PXN V9
  emulatorLauncher/Common/Wheels.cs
Labels: enhancement

#785 Update TeknoParrot.Guns.cs
  emulatorLauncher/Generators/TeknoParrot.Guns.cs
Labels: bug

#786 Update list ExeLauncher DS
  emulatorLauncher/Demulshooter/Demulshooter.cs
Labels: enhancement

#787 Holani features
  .emulationstation/es_features.cfg
Labels: enhancement

#788 Fix reshade
  emulatorLauncher/Demulshooter/Demulshooter.cs
  emulatorLauncher/Generators/TeknoParrot.generator.cs
Labels: bug, enhancement
