Repository RetroBat-Official/emulatorlauncher, pull requests merged in 2025-02, with the labels that each got.

#791 Shadps4 - add a few features
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/ShadPS4.Generator.cs
Labels: enhancement

#795 Add ds_nocrosshair for demulshooter
  .emulationstation/es_features.cfg
  emulatorLauncher/Demulshooter/Demulshooter.cs
  emulatorLauncher/Generators/PortsLauncher.Configuration.cs
Labels: enhancement

#796 Remove disable emulator config
  emulatorLauncher/Generators/Rpcs3.Generator.cs
Labels: enhancement

#797 Vpinball - PUP registration
  emulatorLauncher/Generators/Mame64.Generator.cs
  emulatorLauncher/Generators/MessSystem.cs
  emulatorLauncher/Generators/VPinball.Generator.cs
Labels: Update

#798 VPinball - adapt to latest version stable
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/VPinball.Generator.cs
Labels: Update

#800 Fix libretro offset and add shadps4 .lnk
  EmulatorLauncher.Common/FileTools.cs
  emulatorLauncher/Common/Generator.cs
  emulatorLauncher/Generators/LibRetro.Generator.cs
  emulatorLauncher/Generators/ShadPS4.Generator.cs
Labels: Update

#801 Libretro wrong screen placement - definitive fix
  emulatorLauncher/Generators/LibRetro.Generator.cs
Labels: bug

#807 Add several options
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
  emulatorLauncher/Generators/Pcsx2.Controllers.cs
  emulatorLauncher/Generators/Rpcs3.Generator.cs
  emulatorLauncher/Generators/Ryujinx.Controllers.cs
  emulatorLauncher/Generators/VPinball.Generator.cs
Labels: enhancement, feature request

#809 Fix 2 flycast features
  .emulationstation/es_features.cfg
Labels: bug

#812 Bump 7zip
  7z.dll
  7z.exe
  7za.dll
  7za.exe
  7zxa.dll
Labels: Update

#813 Fix small mistake
  .emulationstation/es_features.cfg
Labels: bug

#816 RetroArch and Cemu
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Cemu.Controllers.cs
  emulatorLauncher/Generators/Cemu.Generator.cs
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
  emulatorLauncher/Generators/LibRetro.Generator.cs
  emulatorLauncher/Generators/Libretro.Controllers.cs
  emulatorLauncher/Generators/Libretro.InputRemap.cs
Labels: Update

#817 Fix vpinball and retroarch bias
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
  emulatorLauncher/Generators/LibRetro.Generator.cs
  emulatorLauncher/Generators/VPinball.Generator.cs
Labels: bug

#818 Libretro update
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
  emulatorLauncher/Generators/Model2.Generator.cs
  emulatorLauncher/Generators/TeknoParrot.generator.cs
  emulatorLauncher/Resources/libretrocoreguns.yml
Labels: Update

#819 Libretro video driver and bias fix
  emulatorLauncher/Common/Generator.cs
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
  emulatorLauncher/Generators/LibRetro.Generator.cs
Labels: bug

#820 Add ability to modify retroarch shorctuts
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
  emulatorLauncher/Generators/LibRetro.Generator.cs
  emulatorLauncher/Generators/Libretro.Controllers.cs
Labels: Update

#821 Libretro update - final
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
  emulatorLauncher/Generators/LibRetro.Generator.cs
Labels: Update

#822 Add j2me core
  .emulationstation/es_features.cfg
  batocera-systems/Resources/batocera-systems.json
  emulatorLauncher/Generators/LibRetro.CoreOptions.cs
  emulatorLauncher/Generators/LibRetro.Generator.cs
Labels: enhancement, feature request

#824 Fix null pointer for dolphin-triforce with nintendo controller
  emulatorLauncher/Generators/Dolphin.Controllers.cs
Labels: bug

#826 Vpinball, snes9x and exclusive fs
  .emulationstation/es_features.cfg
  emulatorLauncher/Generators/Altirra.Generator.cs
  emulatorLauncher/Generators/BigPEmu.Generator.cs
  emulatorLauncher/Generators/Citron.Generator.cs
  emulatorLauncher/Generators/Daphne.Generator.cs
  emulatorLauncher/Generators/Dolphin.Generator.cs
  emulatorLauncher/Generators/Jgenesis.Generator.cs
  emulatorLauncher/Generators/Mesen.Generator.cs
  emulatorLauncher/Generators/Model3.Generator.cs
  emulatorLauncher/Generators/Redream.Generator.cs
  emulatorLauncher/Generators/Rpcs3.Generator.cs
  emulatorLauncher/Generators/ShadPS4.Generator.cs
  emulatorLauncher/Generators/Snes9x.Controllers.cs
  emulatorLauncher/Generators/Sudachi.Generator.cs
  emulatorLauncher/Generators/Suyu.Generator.cs
  emulatorLauncher/Generators/VPinball.Generator.cs
  emulatorLauncher/Generators/Yuzu.Generator.cs
Labels: bug, enhancement, Update

#827 Update retrieval of GUID for bigpemu
  emulatorLauncher/Generators/BigPEmu.Controllers.cs
Labels: Update

#828 BigPEmu get sdl2 version from dll
  emulatorLauncher/Generators/BigPEmu.Generator.cs
Labels: enhancement

#829 Adjustments to Supermodel iteration order for inputs
  emulatorLauncher/Generators/Model3.Controllers.cs
Labels: bug
